from typing import List, Dict, Any, Optional
from datetime import datetime
from uuid import UUID
from pydantic import BaseModel, Field


class ComplianceAuditMetadata(BaseModel):
    audit_id: str
    export_timestamp: datetime
    platform_name: str = "FinSight Institutional Platform"
    engine_version: str = "financial-engine-v1"
    regulatory_framework: str = "Investment Advisers Act §202(a)(11) & SEC Guidance on Algorithmic Models"
    mandatory_disclaimer: str = (
        "Educational and Informational Notice: All research syntheses, financial simulations, "
        "and AI tutor interactions generated by FinSight are provided exclusively for educational, "
        "informational, and analytical modeling purposes. They do not constitute personalized investment "
        "advice, financial endorsements, or broker-dealer solicitations."
    )
    sha256_digest: Optional[str] = None


class ComplianceProfileAudit(BaseModel):
    user_id: UUID
    assessment_date: Optional[datetime]
    risk_tier: Optional[str] = None
    risk_tolerance: Optional[str] = None
    risk_capacity: Optional[str] = None
    investment_horizon: Optional[str] = None
    primary_goal: Optional[str] = None
    experience_level: Optional[str] = None
    liquidity_requirement: Optional[str] = None
    profile_version: Optional[int] = 1


class ComplianceResearchAudit(BaseModel):
    run_id: UUID
    query: str
    ticker: Optional[str]
    status: str
    created_at: datetime
    synthesis_markdown: Optional[str]
    evidence_count: int
    citation_sources: List[Dict[str, Any]]
    jev_claim_evaluations: List[Dict[str, Any]]


class ComplianceSimulationAudit(BaseModel):
    simulation_id: UUID
    engine_version: str
    initial_capital: str
    monthly_contribution: str
    time_horizon_years: int
    annual_return_rate: str
    annual_fee_drag: str
    created_at: datetime
    scenario_terminal_values: Dict[str, str]


class ComplianceTutorAudit(BaseModel):
    evaluation_id: UUID
    timestamp: datetime
    question_id: str
    judgment: str
    confidence_score: float
    routing_action: str
    is_advisory_refusal: bool
    context_type: str
    input_text: Optional[str]


class FullComplianceAuditBundle(BaseModel):
    metadata: ComplianceAuditMetadata
    user_profile: Optional[ComplianceProfileAudit]
    simulations: List[ComplianceSimulationAudit] = []
    research_reports: List[ComplianceResearchAudit] = []
    tutor_safety_logs: List[ComplianceTutorAudit] = []
