from app.db.models import (
    Base,
    User,
    FinancialProfile,
    FinancialProfileAssessment,
    Goal,
    Asset,
    Portfolio,
    Holding,
    Transaction,
    ResearchProject,
    ResearchRun,
    ResearchTask,
    Source,
    DocumentChunk,
    Evidence,
    Claim,
    ClaimSource,
    JevEvaluation,
    SimulationRun,
    Watchlist,
    WatchlistItem,
    WatchlistScan,
    Notification,
    LearningModule,
    LearningProgress,
    QuizAttempt,
    AuditLog,
)


def test_models_metadata_contains_all_26_tables():
    expected_tables = {
        "users",
        "financial_profiles",
        "financial_profile_assessments",
        "goals",
        "assets",
        "portfolios",
        "holdings",
        "transactions",
        "research_projects",
        "research_runs",
        "research_tasks",
        "sources",
        "learning_modules",
        "document_chunks",
        "evidence",
        "claims",
        "claim_sources",
        "jev_evaluations",
        "simulation_runs",
        "watchlists",
        "watchlist_items",
        "watchlist_scans",
        "notifications",
        "learning_progress",
        "quiz_attempts",
        "audit_logs",
    }
    registered_tables = set(Base.metadata.tables.keys())
    assert expected_tables.issubset(registered_tables)
    assert len(registered_tables) >= 26
